image: python:3.9

stages:
  - deploy

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r *.py public # Copy all Python files
    - [ -d templates ] && cp -r templates public || echo "No templates directory found, skipping..."
    - [ -d static ] && cp -r static public || echo "No static directory found, skipping..."
  artifacts:
    paths:
      - public
  only:
    - main
