image: python:3.9

stages:
  - deploy

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r *.py public # Copy all Python files
    - if [ -d templates ]; then cp -r templates public; else echo "No templates directory found, skipping..."; fi
    - if [ -d static ]; then cp -r static public; else echo "No static directory found, skipping..."; fi

  artifacts:
    paths:
      - public
  only:
    - main 
